[project]
name = "explore_stock_analysis"
version = "0.1.0"
description = "Explore various ML algorithms applied to stock market analysis."
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "numpy>=2.3.5",
    "pandas>=2.3.3",
    "scikit-learn>=1.8.0",
    "torch>=2.9.1",
]
